version: "3.9"

services:
  test-db:
    image: mysql:8.0.30
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    # command: --default-authentication-plugin=mysql_native_password --ssl=0
    volumes:
      - ./liquibase/test.sql:/docker-entrypoint-initdb.d/init.sql
      - ./laravel-data:/var/lib/mysql
    networks:
      test-laravel:
        ipv4_address: 10.6.0.3

  web:
    build: .
    restart: on-failure
    ports:
      - "8081:80"
    depends_on:
      - test-db
    env_file:
      - .env
    environment:
      DB_HOST: test-db
      DB_USERNAME: root
    networks:
      test-laravel:
        ipv4_address: 10.6.0.2 # static to allow access from the host
    volumes:
      - .:/var/www/html
volumes:
  laravel-data:

networks:
  test-laravel:
    name: test-laravel
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1
          ip_range: 10.6.1.0/24
