name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
      
    services:
      test-db:
        image: mysql:8.0.30
        ports:
          - "3309:3306"
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        volumes:
          - ./liquibase/test.sql:/docker-entrypoint-initdb.d/init.sql
          - ./laravel-data:/var/lib/mysql

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, dom, fileinfo, mysql
        coverage: xdebug

    - uses: actions/checkout@v3

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
            
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Prepare the application
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        php artisan key:generate
        chmod -R 777 storage bootstrap/cache

    - name: PHP Linting
      run: vendor/bin/pint --test

    - name: Test with phpunit
      run: vendor/bin/phpunit --coverage-text
